language: php
sudo: false

services:
  - mysql

matrix:
  include:
    - php: 5.6
      env: wp_version=latest
    - php: 7.1
      env: wp_version=latest
    - php: 7.1
      env: wp_version=trunk

script:
  - bash ci/prepare.sh $wp_version
  - bash ci/test.sh
